# Generated by Django 6.0 on 2025-12-23 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=100)),
                ('_current_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflowables', to='core.state')),
                ('_workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflowables', to='core.workflow')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='oms_demo.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
