# Generated by Django 6.0 on 2025-12-27 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oms_demo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='_slug',
            field=models.SlugField(default='2025-12-27 14:10:18.852313+00:00', unique=True),
            preserve_default=False,
        ),
    ]
