# Generated by Django 6.0 on 2025-12-27 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oms_demo', '0002_order__slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='_slug',
        ),
    ]
