# Generated by Django 6.0 on 2025-12-27 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oms_demo', '0003_remove_order__slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('waiting_for_payment', 'waiting_for_payment'), ('paid', 'paid')], default='waiting_for_payment'),
        ),
    ]
