# Generated by Django 6.0 on 2025-12-27 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='enter_guard',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='state',
            name='exit_guard',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
