# Generated by Django 6.0 on 2025-12-27 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_state_enter_guard_state_exit_guard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('from_states', models.ManyToManyField(related_name='transitions_from', to='core.state')),
                ('to_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transition_to', to='core.state')),
            ],
        ),
        migrations.DeleteModel(
            name='Movement',
        ),
    ]
