# Generated by Django 6.0 on 2025-12-28 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_transition_delete_movement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transition',
            name='from_states',
        ),
        migrations.RemoveField(
            model_name='transition',
            name='slug',
        ),
        migrations.AddField(
            model_name='action',
            name='on_finish_transition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.transition'),
        ),
        migrations.AddField(
            model_name='state',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transition',
            name='from_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transition_from', to='core.state'),
        ),
    ]
