# Generated by Django 6.0 on 2025-12-28 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_transition_from_states_remove_transition_slug_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transition',
            unique_together={('from_state', 'to_state')},
        ),
    ]
